#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SURTEX_SA
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SURTEX_SA")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void Inserttbl_cargo(tbl_cargo instance);
    partial void Updatetbl_cargo(tbl_cargo instance);
    partial void Deletetbl_cargo(tbl_cargo instance);
    partial void Inserttbl_departamento(tbl_departamento instance);
    partial void Updatetbl_departamento(tbl_departamento instance);
    partial void Deletetbl_departamento(tbl_departamento instance);
    partial void Inserttbl_empresa(tbl_empresa instance);
    partial void Updatetbl_empresa(tbl_empresa instance);
    partial void Deletetbl_empresa(tbl_empresa instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["SURTEX_SAConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_cargo> tbl_cargo
		{
			get
			{
				return this.GetTable<tbl_cargo>();
			}
		}
		
		public System.Data.Linq.Table<tbl_departamento> tbl_departamento
		{
			get
			{
				return this.GetTable<tbl_departamento>();
			}
		}
		
		public System.Data.Linq.Table<tbl_empresa> tbl_empresa
		{
			get
			{
				return this.GetTable<tbl_empresa>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.eliminar_cargo")]
		public int eliminar_cargo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> car_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), car_id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.guardar_cargo")]
		public int guardar_cargo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string car_nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string car_descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> dep_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), car_nombre, car_descripcion, dep_id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.modificar_cargo")]
		public int modificar_cargo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string car_nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string car_descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> dep_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> car_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), car_nombre, car_descripcion, dep_id, car_id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.mostrar_cargo")]
		public ISingleResult<mostrar_cargoResult> mostrar_cargo()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<mostrar_cargoResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_cargo")]
	public partial class tbl_cargo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _car_id;
		
		private string _car_nombre;
		
		private string _car_descripcion;
		
		private System.Nullable<char> _car_estado;
		
		private int _dep_id;
		
		private EntityRef<tbl_departamento> _tbl_departamento;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncar_idChanging(int value);
    partial void Oncar_idChanged();
    partial void Oncar_nombreChanging(string value);
    partial void Oncar_nombreChanged();
    partial void Oncar_descripcionChanging(string value);
    partial void Oncar_descripcionChanged();
    partial void Oncar_estadoChanging(System.Nullable<char> value);
    partial void Oncar_estadoChanged();
    partial void Ondep_idChanging(int value);
    partial void Ondep_idChanged();
    #endregion
		
		public tbl_cargo()
		{
			this._tbl_departamento = default(EntityRef<tbl_departamento>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_car_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int car_id
		{
			get
			{
				return this._car_id;
			}
			set
			{
				if ((this._car_id != value))
				{
					this.Oncar_idChanging(value);
					this.SendPropertyChanging();
					this._car_id = value;
					this.SendPropertyChanged("car_id");
					this.Oncar_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_car_nombre", DbType="VarChar(100)")]
		public string car_nombre
		{
			get
			{
				return this._car_nombre;
			}
			set
			{
				if ((this._car_nombre != value))
				{
					this.Oncar_nombreChanging(value);
					this.SendPropertyChanging();
					this._car_nombre = value;
					this.SendPropertyChanged("car_nombre");
					this.Oncar_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_car_descripcion", DbType="VarChar(100)")]
		public string car_descripcion
		{
			get
			{
				return this._car_descripcion;
			}
			set
			{
				if ((this._car_descripcion != value))
				{
					this.Oncar_descripcionChanging(value);
					this.SendPropertyChanging();
					this._car_descripcion = value;
					this.SendPropertyChanged("car_descripcion");
					this.Oncar_descripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_car_estado", DbType="Char(1)")]
		public System.Nullable<char> car_estado
		{
			get
			{
				return this._car_estado;
			}
			set
			{
				if ((this._car_estado != value))
				{
					this.Oncar_estadoChanging(value);
					this.SendPropertyChanging();
					this._car_estado = value;
					this.SendPropertyChanged("car_estado");
					this.Oncar_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dep_id", DbType="Int NOT NULL")]
		public int dep_id
		{
			get
			{
				return this._dep_id;
			}
			set
			{
				if ((this._dep_id != value))
				{
					if (this._tbl_departamento.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ondep_idChanging(value);
					this.SendPropertyChanging();
					this._dep_id = value;
					this.SendPropertyChanged("dep_id");
					this.Ondep_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_departamento_tbl_cargo", Storage="_tbl_departamento", ThisKey="dep_id", OtherKey="dep_id", IsForeignKey=true)]
		public tbl_departamento tbl_departamento
		{
			get
			{
				return this._tbl_departamento.Entity;
			}
			set
			{
				tbl_departamento previousValue = this._tbl_departamento.Entity;
				if (((previousValue != value) 
							|| (this._tbl_departamento.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_departamento.Entity = null;
						previousValue.tbl_cargo.Remove(this);
					}
					this._tbl_departamento.Entity = value;
					if ((value != null))
					{
						value.tbl_cargo.Add(this);
						this._dep_id = value.dep_id;
					}
					else
					{
						this._dep_id = default(int);
					}
					this.SendPropertyChanged("tbl_departamento");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_departamento")]
	public partial class tbl_departamento : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _dep_id;
		
		private string _dep_nombre;
		
		private string _dep_nombre_jefe;
		
		private string _dep_apellido_jefe;
		
		private string _dep_descripcion;
		
		private System.Nullable<char> _dep_estado;
		
		private int _emp_id;
		
		private EntitySet<tbl_cargo> _tbl_cargo;
		
		private EntityRef<tbl_empresa> _tbl_empresa;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ondep_idChanging(int value);
    partial void Ondep_idChanged();
    partial void Ondep_nombreChanging(string value);
    partial void Ondep_nombreChanged();
    partial void Ondep_nombre_jefeChanging(string value);
    partial void Ondep_nombre_jefeChanged();
    partial void Ondep_apellido_jefeChanging(string value);
    partial void Ondep_apellido_jefeChanged();
    partial void Ondep_descripcionChanging(string value);
    partial void Ondep_descripcionChanged();
    partial void Ondep_estadoChanging(System.Nullable<char> value);
    partial void Ondep_estadoChanged();
    partial void Onemp_idChanging(int value);
    partial void Onemp_idChanged();
    #endregion
		
		public tbl_departamento()
		{
			this._tbl_cargo = new EntitySet<tbl_cargo>(new Action<tbl_cargo>(this.attach_tbl_cargo), new Action<tbl_cargo>(this.detach_tbl_cargo));
			this._tbl_empresa = default(EntityRef<tbl_empresa>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dep_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int dep_id
		{
			get
			{
				return this._dep_id;
			}
			set
			{
				if ((this._dep_id != value))
				{
					this.Ondep_idChanging(value);
					this.SendPropertyChanging();
					this._dep_id = value;
					this.SendPropertyChanged("dep_id");
					this.Ondep_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dep_nombre", DbType="VarChar(100)")]
		public string dep_nombre
		{
			get
			{
				return this._dep_nombre;
			}
			set
			{
				if ((this._dep_nombre != value))
				{
					this.Ondep_nombreChanging(value);
					this.SendPropertyChanging();
					this._dep_nombre = value;
					this.SendPropertyChanged("dep_nombre");
					this.Ondep_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dep_nombre_jefe", DbType="VarChar(100)")]
		public string dep_nombre_jefe
		{
			get
			{
				return this._dep_nombre_jefe;
			}
			set
			{
				if ((this._dep_nombre_jefe != value))
				{
					this.Ondep_nombre_jefeChanging(value);
					this.SendPropertyChanging();
					this._dep_nombre_jefe = value;
					this.SendPropertyChanged("dep_nombre_jefe");
					this.Ondep_nombre_jefeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dep_apellido_jefe", DbType="VarChar(100)")]
		public string dep_apellido_jefe
		{
			get
			{
				return this._dep_apellido_jefe;
			}
			set
			{
				if ((this._dep_apellido_jefe != value))
				{
					this.Ondep_apellido_jefeChanging(value);
					this.SendPropertyChanging();
					this._dep_apellido_jefe = value;
					this.SendPropertyChanged("dep_apellido_jefe");
					this.Ondep_apellido_jefeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dep_descripcion", DbType="VarChar(100)")]
		public string dep_descripcion
		{
			get
			{
				return this._dep_descripcion;
			}
			set
			{
				if ((this._dep_descripcion != value))
				{
					this.Ondep_descripcionChanging(value);
					this.SendPropertyChanging();
					this._dep_descripcion = value;
					this.SendPropertyChanged("dep_descripcion");
					this.Ondep_descripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dep_estado", DbType="Char(1)")]
		public System.Nullable<char> dep_estado
		{
			get
			{
				return this._dep_estado;
			}
			set
			{
				if ((this._dep_estado != value))
				{
					this.Ondep_estadoChanging(value);
					this.SendPropertyChanging();
					this._dep_estado = value;
					this.SendPropertyChanged("dep_estado");
					this.Ondep_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emp_id", DbType="Int NOT NULL")]
		public int emp_id
		{
			get
			{
				return this._emp_id;
			}
			set
			{
				if ((this._emp_id != value))
				{
					if (this._tbl_empresa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onemp_idChanging(value);
					this.SendPropertyChanging();
					this._emp_id = value;
					this.SendPropertyChanged("emp_id");
					this.Onemp_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_departamento_tbl_cargo", Storage="_tbl_cargo", ThisKey="dep_id", OtherKey="dep_id")]
		public EntitySet<tbl_cargo> tbl_cargo
		{
			get
			{
				return this._tbl_cargo;
			}
			set
			{
				this._tbl_cargo.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_empresa_tbl_departamento", Storage="_tbl_empresa", ThisKey="emp_id", OtherKey="emp_id", IsForeignKey=true)]
		public tbl_empresa tbl_empresa
		{
			get
			{
				return this._tbl_empresa.Entity;
			}
			set
			{
				tbl_empresa previousValue = this._tbl_empresa.Entity;
				if (((previousValue != value) 
							|| (this._tbl_empresa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_empresa.Entity = null;
						previousValue.tbl_departamento.Remove(this);
					}
					this._tbl_empresa.Entity = value;
					if ((value != null))
					{
						value.tbl_departamento.Add(this);
						this._emp_id = value.emp_id;
					}
					else
					{
						this._emp_id = default(int);
					}
					this.SendPropertyChanged("tbl_empresa");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_cargo(tbl_cargo entity)
		{
			this.SendPropertyChanging();
			entity.tbl_departamento = this;
		}
		
		private void detach_tbl_cargo(tbl_cargo entity)
		{
			this.SendPropertyChanging();
			entity.tbl_departamento = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_empresa")]
	public partial class tbl_empresa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _emp_id;
		
		private string _emp_ruc;
		
		private string _emp_representante_legal;
		
		private string _emp_nombre;
		
		private string _emp_direccion;
		
		private System.Nullable<int> _emp_telefono;
		
		private System.Nullable<char> _emp_estado;
		
		private EntitySet<tbl_departamento> _tbl_departamento;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onemp_idChanging(int value);
    partial void Onemp_idChanged();
    partial void Onemp_rucChanging(string value);
    partial void Onemp_rucChanged();
    partial void Onemp_representante_legalChanging(string value);
    partial void Onemp_representante_legalChanged();
    partial void Onemp_nombreChanging(string value);
    partial void Onemp_nombreChanged();
    partial void Onemp_direccionChanging(string value);
    partial void Onemp_direccionChanged();
    partial void Onemp_telefonoChanging(System.Nullable<int> value);
    partial void Onemp_telefonoChanged();
    partial void Onemp_estadoChanging(System.Nullable<char> value);
    partial void Onemp_estadoChanged();
    #endregion
		
		public tbl_empresa()
		{
			this._tbl_departamento = new EntitySet<tbl_departamento>(new Action<tbl_departamento>(this.attach_tbl_departamento), new Action<tbl_departamento>(this.detach_tbl_departamento));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emp_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int emp_id
		{
			get
			{
				return this._emp_id;
			}
			set
			{
				if ((this._emp_id != value))
				{
					this.Onemp_idChanging(value);
					this.SendPropertyChanging();
					this._emp_id = value;
					this.SendPropertyChanged("emp_id");
					this.Onemp_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emp_ruc", DbType="VarChar(100)")]
		public string emp_ruc
		{
			get
			{
				return this._emp_ruc;
			}
			set
			{
				if ((this._emp_ruc != value))
				{
					this.Onemp_rucChanging(value);
					this.SendPropertyChanging();
					this._emp_ruc = value;
					this.SendPropertyChanged("emp_ruc");
					this.Onemp_rucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emp_representante_legal", DbType="VarChar(100)")]
		public string emp_representante_legal
		{
			get
			{
				return this._emp_representante_legal;
			}
			set
			{
				if ((this._emp_representante_legal != value))
				{
					this.Onemp_representante_legalChanging(value);
					this.SendPropertyChanging();
					this._emp_representante_legal = value;
					this.SendPropertyChanged("emp_representante_legal");
					this.Onemp_representante_legalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emp_nombre", DbType="VarChar(100)")]
		public string emp_nombre
		{
			get
			{
				return this._emp_nombre;
			}
			set
			{
				if ((this._emp_nombre != value))
				{
					this.Onemp_nombreChanging(value);
					this.SendPropertyChanging();
					this._emp_nombre = value;
					this.SendPropertyChanged("emp_nombre");
					this.Onemp_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emp_direccion", DbType="VarChar(100)")]
		public string emp_direccion
		{
			get
			{
				return this._emp_direccion;
			}
			set
			{
				if ((this._emp_direccion != value))
				{
					this.Onemp_direccionChanging(value);
					this.SendPropertyChanging();
					this._emp_direccion = value;
					this.SendPropertyChanged("emp_direccion");
					this.Onemp_direccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emp_telefono", DbType="Int")]
		public System.Nullable<int> emp_telefono
		{
			get
			{
				return this._emp_telefono;
			}
			set
			{
				if ((this._emp_telefono != value))
				{
					this.Onemp_telefonoChanging(value);
					this.SendPropertyChanging();
					this._emp_telefono = value;
					this.SendPropertyChanged("emp_telefono");
					this.Onemp_telefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emp_estado", DbType="Char(1)")]
		public System.Nullable<char> emp_estado
		{
			get
			{
				return this._emp_estado;
			}
			set
			{
				if ((this._emp_estado != value))
				{
					this.Onemp_estadoChanging(value);
					this.SendPropertyChanging();
					this._emp_estado = value;
					this.SendPropertyChanged("emp_estado");
					this.Onemp_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_empresa_tbl_departamento", Storage="_tbl_departamento", ThisKey="emp_id", OtherKey="emp_id")]
		public EntitySet<tbl_departamento> tbl_departamento
		{
			get
			{
				return this._tbl_departamento;
			}
			set
			{
				this._tbl_departamento.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_departamento(tbl_departamento entity)
		{
			this.SendPropertyChanging();
			entity.tbl_empresa = this;
		}
		
		private void detach_tbl_departamento(tbl_departamento entity)
		{
			this.SendPropertyChanging();
			entity.tbl_empresa = null;
		}
	}
	
	public partial class mostrar_cargoResult
	{
		
		private int _car_id;
		
		private string _car_nombre;
		
		private string _car_descripcion;
		
		private System.Nullable<char> _car_estado;
		
		private int _dep_id;
		
		private string _dep_nombre;
		
		public mostrar_cargoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_car_id", DbType="Int NOT NULL")]
		public int car_id
		{
			get
			{
				return this._car_id;
			}
			set
			{
				if ((this._car_id != value))
				{
					this._car_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_car_nombre", DbType="VarChar(100)")]
		public string car_nombre
		{
			get
			{
				return this._car_nombre;
			}
			set
			{
				if ((this._car_nombre != value))
				{
					this._car_nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_car_descripcion", DbType="VarChar(100)")]
		public string car_descripcion
		{
			get
			{
				return this._car_descripcion;
			}
			set
			{
				if ((this._car_descripcion != value))
				{
					this._car_descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_car_estado", DbType="Char(1)")]
		public System.Nullable<char> car_estado
		{
			get
			{
				return this._car_estado;
			}
			set
			{
				if ((this._car_estado != value))
				{
					this._car_estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dep_id", DbType="Int NOT NULL")]
		public int dep_id
		{
			get
			{
				return this._dep_id;
			}
			set
			{
				if ((this._dep_id != value))
				{
					this._dep_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dep_nombre", DbType="VarChar(100)")]
		public string dep_nombre
		{
			get
			{
				return this._dep_nombre;
			}
			set
			{
				if ((this._dep_nombre != value))
				{
					this._dep_nombre = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
